name : variables
on : push
jobs : 
  print :
    runs-on : ubuntu-latest
    env : 
      USERNAME : ${{ vars.USERNAME }}  # 변수 참조
    steps :
      - run : echo "${USERNAME}"  
      # vars 콘텍스트를 통해 접근할 수 있다. 콘텍스트 참조시 잊지말고 중간 환경변수를 경유하여 접근해야 한다. 